spring.application.name=sendMail
server.port=${PORT:8080}
#Tu proveedor de correo electronico
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#Tu correo electrónico
spring.mail.username=${MAIL}
#Tu clave(contrasena) de aplicacion generada por el proveedor de correo.
spring.mail.password=${PASSWORD}
#Tu nombre o el nombre que quieres que aparezca en el correo de sendResponse()
spring.owner.name=${NAME}
spring.mail.properties.mail.smtp.auth =true
spring.mail.properties.mail.smtp.starttls.enable =true

