spring.application.name=sendMail
server.port=${PORT:8080}

spring.owner.mail=${MAIL}
spring.owner.name=${NAME}
app.cors.allowed-origins=${URL_CORS}
brevo.api.key=${BREVO_API_KEY}

spring.mail.properties.mail.debug=true